[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ['*']
gas_reports_ignore = []

[fmt] 
int_types = "short"
line_length = 120
bracket_spacing = true
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "single"
ignore = ['./script/**/*']
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
